---
swagger: "2.0"
info:
  description: "Traduction commandes GET vers les PrimitivesWS du Robot Poppy"
  version: "1.0.1"
  title: "Controller Poppy API"
host: "localhost:8080"
basePath: "/"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /test/behave:
    get:
      tags:
      - "Primitive Behave"
      summary: "Messages"
      description: "swap_behave\n"
      parameters:
      - name: "name"
        in: "query"
        description: "Behave Primitive"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Poppy Behave"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /chatterbot:
    get:
      tags:
      - "Chatterbot"
      summary: "Messages"
      description: "Chatterbot\n"
      parameters:
      - name: "msg"
        in: "query"
        description: "Message to send"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Poppy Speak through his mic"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /table/scan:
    get:
      tags:
      - "AWSTable"
      summary: "Scan of tables"
      description: "AWS Table Management\n"
      parameters:
      - name: "adress"
        in: "query"
        description: "AWS Table Management"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Scan successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /multi/set:
    get:
      tags:
      - "Multiplication"
      summary: "Multiplication"
      description: "Multiplication set the equation"
      parameters:
      - name: "param"
        in: "query"
        description: "Number for Mutiplication (table of 8)"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Play multiplication"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /multi/answer:
    get:
      tags:
      - "Multiplication"
      summary: "Multiplication"
      description: "Multiplication answer of the child"
      parameters:
      - name: "param"
        in: "query"
        description: "Number for Mutiplication (table of 8)"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Play multiplication"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /multi/right_answer:
    get:
      tags:
      - "Multiplication"
      summary: "Multiplication"
      description: "Multiplication answer of the child"
      parameters:
      - name: "param"
        in: "query"
        description: "Number for Mutiplication (table of 8)"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Play multiplication"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /multi/false_answer:
    get:
      tags:
      - "Multiplication"
      summary: "Multiplication"
      description: "Multiplication answer of the child"
      parameters:
      - name: "param"
        in: "query"
        description: "Number for Mutiplication (table of 8)"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Play multiplication"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /multi/learn_all_multiplications:
    get:
      tags:
      - "Multiplication"
      summary: "Multiplication"
      description: "Multiplication answer of the child"
      parameters:
      - name: "param"
        in: "query"
        description: "Number for Mutiplication (table of 8)"
        required: false
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "Play multiplication"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Info"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Info:
    type: "object"
    properties:
      info:
        type: "string"
        description: "Info Return"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
